// mypages.js
// 2023-03-01

exports.genIndex = function(data){
    var pagHTML = `
    <!DOCTYPE html>
    <head>
        <meta charset= "UTF-8">
        <title>Índice</title>
        <link rel="stylesheet" href = "w3.css"/>
    </head>

        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-red">
                    <h1>TPC3 - Base de Dados de Pessoas</h1>
                </header>
        
                <div class="w3-container">
                   <div class="w3-container">

                <ol w3-hoverable class="w3-ul w3-xxlarge">
                   <li class ="w3-ul w3-hoverable"><a href="/pessoas">Lista das Pessoas</a></li>
                   <li class ="w3-ul w3-hoverable"><a href="/sexo">Distribuição por Sexo</a></li>
                   <li class ="w3-ul w3-hoverable"><a href="/desporto">Distribuição por Desporto</a></li>
                   <li class ="w3-ul w3-hoverable"><a href="/profissao">Top 10 de Profissões</a></li>
                </ol>

                <footer class="w3-container w3-blue">
                    <h5>João Loureiro - a97257 | Engenharia Web 2023 - Universidade do Minho</h5>
                    <h5>Generated by server: ${data}</h5>
                </footer>
            </div>
        </body>
    </html>
                `

    return pagHTML
}

exports.genListaPes = function(lista, data){
    var pagHTML = `
    <!DOCTYPE html>
    <head>
        <meta charset= "UTF-8">
        <title>Lista de Pessoas</title>
        <link rel="stylesheet" href = "w3.css"/>
    </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-red">
                    <h1>Lista de Pessoas na Base de Dados (${lista.length})</h1>
                </header>
        
                <div class="w3-container">
                   <div class="w3-container">

                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Idade</th>
                            <th>Sexo</th>
                            <th>Cidade</th>
                        </tr>`

    for(let i=0; i<lista.length; i++){
        pagHTML += `
                <tr>
                        <td>${lista[i].id}</td>
                        <td>
                            <a href="http://localhost:7778/pessoas/${lista[i].id}">
                            ${lista[i].nome}
                            </a>
                        </td>
                        <td>${lista[i].idade}</td>
                        <td>${lista[i].sexo}</td>
                        <td>${lista[i].morada.cidade}</td>
                </tr>
        `
    }
   
    pagHTML += `
                    </table>
                    </div>
        
                <footer class="w3-container w3-blue">
                    <h5>João Loureiro - a97257 | Engenharia Web 2023 - Universidade do Minho</h5>
                    <h5>Generated by server: ${data}</h5>
                </footer>
            </div>
        </body>
</html>
    `
    return pagHTML
}

exports.genPessoaPage = function(pessoa, data){
    var pagHTML = `
    <!DOCTYPE html>
    <head>
        <meta charset= "UTF-8">
        <title>About people...</title>
        <link rel="stylesheet" href = "w3.css"/>
    </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-red">
                    <h1>${pessoa.nome}</h1>
                </header>
        
                <div class="w3-container">
                `

    //TODO: TERMINAR CONSTRUIR PAG HTML
    pagHTML += `
                    </div>
        
                <footer class="w3-container w3-blue">
                    <h5>João Loureiro - a97257 | Engenharia Web 2023 - Universidade do Minho</h5>
                    <h5>Generated by server: ${data}</h5>
                </footer>
            </div>
        </body>
</html>
    `
    return pagHTML
}

exports.genPagDistSexo = function(lista,data){
    var sexos = {}
    for(let i=0; i<lista.length;i++){
        if (!(sexos.hasOwnProperty(lista[i].sexo))){
            sexos[lista[i].sexo] = 0
        }
        sexos[lista[i].sexo] = sexos[lista[i].sexo] + 1
    }

    var pagHTML = `
            <!DOCTYPE html>
            <head>
                <meta charset= "UTF-8">
                <title>Distribuição por Sexo</title>
                <link rel="stylesheet" href = "w3.css"/>
            </head>
                <body>
                    <div class="w3-card-4">
                        <header class="w3-container w3-red">
                            <h1>Distribuição por Sexo</h1>
                        </header>
                
                        <div class="w3-container">
                            <div class="w3-container">

                            <table class="w3-table-all">
                                <tr>
                                    <th>Sexo</th>
                                    <th>Número de Pessoas</th>
                                </tr>`
    
    for(const [sex,qnt] of Object.entries(sexos)){
        pagHTML += `
                <tr>
                        <td>${sex}</td>
                        <td>
                            <a href="http://localhost:7778/sexo/${sex}">
                            ${qnt}
                            </a>
                        </td>
                </tr>
        `
    }
    
    pagHTML += `
                        </table>
                        </div>
            
                    <footer class="w3-container w3-blue">
                        <h5>João Loureiro - a97257 | Engenharia Web 2023 - Universidade do Minho</h5>
                        <h5>Generated by server: ${data}</h5>
                    </footer>
                </div>
                    </body>
            </html>
        `
    
        return pagHTML
}

exports.genPagSexoEscolhido = function(sexo,lista,data){
    var pagHTML = `
    <!DOCTYPE html>
    <head>
        <meta charset= "UTF-8">
        <title>Sexo ${sexo}</title>
        <link rel="stylesheet" href = "w3.css"/>
    </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-red">
                    <h1>Lista de Pessoas do sexo ${sexo}</h1>
                </header>
        
                <div class="w3-container">
                   <div class="w3-container">

                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Idade</th>
                            <th>Sexo</th>
                            <th>Cidade</th>
                        </tr>`

    for(let i=0; i<lista.length; i++){
        if (lista[i].sexo == sexo){
            pagHTML += `
                <tr>
                        <td>${lista[i].id}</td>
                        <td>
                            <a href="http://localhost:7778/pessoas/${lista[i].id}">
                            ${lista[i].nome}
                            </a>
                        </td>
                        <td>${lista[i].idade}</td>
                        <td>${lista[i].sexo}</td>
                        <td>${lista[i].morada.cidade}</td>
                </tr>
        `

        }
    }
   
    pagHTML += `
                    </table>
                    </div>
        
                <footer class="w3-container w3-blue">
                    <h5>João Loureiro - a97257 | Engenharia Web 2023 - Universidade do Minho</h5>
                    <h5>Generated by server: ${data}</h5>
                </footer>
            </div>
        </body>
</html>
    `
    return pagHTML

}