// mypages.js
// 2023-03-01

exports.genIndex = function(data){
    var pagHTML = `
    <!DOCTYPE html>
    <head>
        <meta charset= "UTF-8">
        <title>Índice</title>
        <link rel="stylesheet" href = "w3.css"/>
    </head>

        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-red">
                    <h1>TPC3 - Base de Dados de Pessoas</h1>
                </header>
        
                <div class="w3-container">
                   <div class="w3-container">

                <ol w3-hoverable class="w3-ul w3-xxlarge">
                   <li class ="w3-ul w3-hoverable"><a href="/pessoas">Lista das Pessoas (Por ID)</a></li>
                   <li class ="w3-ul w3-hoverable"><a href="/pessoas/alfa">Lista das Pessoas (A-Z)</a></li>
                   <li class ="w3-ul w3-hoverable"><a href="/sexo">Distribuição por Sexo</a></li>
                   <li class ="w3-ul w3-hoverable"><a href="/desporto">Distribuição por Desporto</a></li>
                   <li class ="w3-ul w3-hoverable"><a href="/profissao">Top 10 de Profissões</a></li>
                </ol>

                <footer class="w3-container w3-blue">
                    <h5>João Loureiro - a97257 | Engenharia Web 2023 - Universidade do Minho</h5>
                    <h5>Generated by server: ${data}</h5>
                </footer>
            </div>
        </body>
    </html>
                `

    return pagHTML
}

exports.genListaPes = function(lista, data){
    var pagHTML = `
    <!DOCTYPE html>
    <head>
        <meta charset= "UTF-8">
        <title>Lista de Pessoas</title>
        <link rel="stylesheet" href = "w3.css"/>
    </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-red">
                    <h1>Lista de Pessoas na Base de Dados (${lista.length})</h1>
                </header>
        
                <div class="w3-container">
                   <div class="w3-container">

                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Idade</th>
                            <th>Sexo</th>
                            <th>Cidade</th>
                        </tr>`

    for(let i=0; i<lista.length; i++){
        pagHTML += `
                <tr>
                        <td>${lista[i].id}</td>
                        <td>
                            <a href="http://localhost:7778/pessoas/${lista[i].id}">
                            ${lista[i].nome}
                            </a>
                        </td>
                        <td>${lista[i].idade}</td>
                        <td>${lista[i].sexo}</td>
                        <td>${lista[i].morada.cidade}</td>
                </tr>
        `
    }
   
    pagHTML += `
                    </table>
                    </div>
        
                <footer class="w3-container w3-blue">
                    <h5>João Loureiro - a97257 | Engenharia Web 2023 - Universidade do Minho</h5>
                    <h5>Generated by server: ${data}</h5>
                </footer>
            </div>
        </body>
</html>
    `
    return pagHTML
}

exports.genListaPesID = function(lis, data){

    for(let i = 0;i<lis.length;i++){
        lis[i].id = parseInt(lis[i].id.slice(1))
    }

    let lista = lis.sort(
        (p1, p2) => (p1.id< p2.id) ? -1 : 1
    )

    var pagHTML = `
    <!DOCTYPE html>
    <head>
        <meta charset= "UTF-8">
        <title>Lista de Pessoas</title>
        <link rel="stylesheet" href = "w3.css"/>
    </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-red">
                    <h1>Lista de Pessoas na Base de Dados (${lista.length})</h1>
                </header>
        
                <div class="w3-container">
                   <div class="w3-container">

                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Idade</th>
                            <th>Sexo</th>
                            <th>Cidade</th>
                        </tr>`

    for(let i=0; i<lista.length; i++){
        pagHTML += `
                <tr>
                        <td>p${lista[i].id}</td>
                        <td>
                            <a href="http://localhost:7778/pessoas/p${lista[i].id}">
                            ${lista[i].nome}
                            </a>
                        </td>
                        <td>${lista[i].idade}</td>
                        <td>${lista[i].sexo}</td>
                        <td>${lista[i].morada.cidade}</td>
                </tr>
        `
    }
   
    pagHTML += `
                    </table>
                    </div>
        
                <footer class="w3-container w3-blue">
                    <h5>João Loureiro - a97257 | Engenharia Web 2023 - Universidade do Minho</h5>
                    <h5>Generated by server: ${data}</h5>
                </footer>
            </div>
        </body>
</html>
    `
    return pagHTML
}

// FONTE DA PRIMEIRA PARTE: https://stackoverflow.com/questions/1026069/how-do-i-make-the-first-letter-of-a-string-uppercase-in-javascript
function trataAtributo(string) {
    var aux =  string.charAt(0).toUpperCase() + string.slice(1)
    var res = aux.replaceAll("_"," ")
    return res
}

exports.genPessoaPage = function(pessoa, data){
    var pagHTML = `
    <!DOCTYPE html>
    <head>
        <meta charset= "UTF-8">
        <title>Sobre ${pessoa.nome}</title>
        <link rel="stylesheet" href = "w3.css"/>
    </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-red">
                    <h1>${pessoa.nome}</h1>
                </header>
        
                <div class="w3-container">
                `

    const atributos = Object.keys(pessoa)

    for(let i=0; i<atributos.length;i++){
        // se for array
        if(Array.isArray(pessoa[atributos[i]])){
            pagHTML += `
                <div class="w3-panel w3-sand">
                    <p><b>${trataAtributo(atributos[i])}:</b> 
                    `     
                
            for(let j = 0; j<pessoa[atributos[i]].length; j++){
                    pagHTML += `
                    ${pessoa[atributos[i]][j]}
                        `
                             
                if(j != (pessoa[atributos[i]].length - 1)){
                    pagHTML += ','
                }
            }

            pagHTML += `
                    </p>
                </div>
            `      
        }

        // se for dicionario
        else if (typeof pessoa[atributos[i]] == "object"){
            for(const [at,val] of Object.entries(pessoa[atributos[i]])){
                if (val == true){
                    pagHTML += `
                            <div class="w3-panel w3-sand">
                                <p><b>${trataAtributo(at)}?:</b> Sim</p>
                            </div>
                        `
                }

                else if (val == false){
                    pagHTML += `
                            <div class="w3-panel w3-sand">
                                <p><b>${trataAtributo(at)}?:</b> Não</p>
                            </div>
                        `
                }

                else{
                    pagHTML += `
                        <div class="w3-panel w3-sand">
                            <p><b>${trataAtributo(at)}:</b> ${val}</p>
                        </div>
                    `
                }
            }

        }

        // caso seja um so valor
        else{
            pagHTML += `
                <div class="w3-panel w3-sand">
                    <p><b>${trataAtributo(atributos[i])}:</b> ${pessoa[atributos[i]]}</p>
                </div>
            `
        }

    }

    pagHTML += `
                    </div>
        
                <footer class="w3-container w3-blue">
                    <h5>João Loureiro - a97257 | Engenharia Web 2023 - Universidade do Minho</h5>
                    <h5>Generated by server: ${data}</h5>
                </footer>
            </div>
        </body>
</html>
    `
    return pagHTML
}

exports.genPagDistSexo = function(lista,data){
    var sexos = {}
    for(let i=0; i<lista.length;i++){
        if (!(sexos.hasOwnProperty(lista[i].sexo))){
            sexos[lista[i].sexo] = 0
        }
        sexos[lista[i].sexo] = sexos[lista[i].sexo] + 1
    }

    var sexOrd = Object.keys(sexos).map(
        (key) => {return [key,sexos[key]]}
    )

    sexOrd.sort(
        (p1,p2) => {return p2[1] - p1[1]}
    )

    var pagHTML = `
            <!DOCTYPE html>
            <head>
                <meta charset= "UTF-8">
                <title>Distribuição por Sexo</title>
                <link rel="stylesheet" href = "w3.css"/>
            </head>
                <body>
                    <div class="w3-card-4">
                        <header class="w3-container w3-red">
                            <h1>Distribuição por Sexo</h1>
                        </header>
                
                        <div class="w3-container">
                            <div class="w3-container">

                            <table class="w3-table-all">
                                <tr>
                                    <th>Sexo</th>
                                    <th>Número de Pessoas</th>
                                </tr>`
    
    for(let i=0; i<sexOrd.length;i++){
        pagHTML += `
                <tr>
                        <td>${sexOrd[i][0]}</td>
                        <td>
                            <a href="http://localhost:7778/sexo/${sexOrd[i][0]}">
                            ${sexOrd[i][1]}
                            </a>
                        </td>
                </tr>
        `
    }
    
    pagHTML += `
                        </table>
                        </div>
            
                    <footer class="w3-container w3-blue">
                        <h5>João Loureiro - a97257 | Engenharia Web 2023 - Universidade do Minho</h5>
                        <h5>Generated by server: ${data}</h5>
                    </footer>
                </div>
                    </body>
            </html>
        `
    
        return pagHTML
}

exports.genPagSexoEscolhido = function(sexo,lista,data){
    var pagHTML = `
    <!DOCTYPE html>
    <head>
        <meta charset= "UTF-8">
        <title>Sexo ${sexo}</title>
        <link rel="stylesheet" href = "w3.css"/>
    </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-red">
                    <h1>Lista de Pessoas do sexo ${sexo}</h1>
                </header>
        
                <div class="w3-container">
                   <div class="w3-container">

                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Idade</th>
                            <th>Sexo</th>
                            <th>Cidade</th>
                        </tr>`

    for(let i=0; i<lista.length; i++){
        if (lista[i].sexo == sexo){
            pagHTML += `
                <tr>
                        <td>${lista[i].id}</td>
                        <td>
                            <a href="http://localhost:7778/pessoas/${lista[i].id}">
                            ${lista[i].nome}
                            </a>
                        </td>
                        <td>${lista[i].idade}</td>
                        <td>${lista[i].sexo}</td>
                        <td>${lista[i].morada.cidade}</td>
                </tr>
        `

        }
    }
   
    pagHTML += `
                    </table>
                    </div>
        
                <footer class="w3-container w3-blue">
                    <h5>João Loureiro - a97257 | Engenharia Web 2023 - Universidade do Minho</h5>
                    <h5>Generated by server: ${data}</h5>
                </footer>
            </div>
        </body>
</html>
    `
    return pagHTML

}

exports.genPagDistDesporto = function(lista,data){
    var desps = {}

    for(let i=0; i<lista.length;i++){
        if (lista[i].desportos != null){
            for(let j=0; j<lista[i].desportos.length;j++){
                if (!(desps.hasOwnProperty(lista[i].desportos[j]))){
                    desps[lista[i].desportos[j]] = 0
                }
                desps[lista[i].desportos[j]] = desps[lista[i].desportos[j]] + 1
            }
        }
    }

    var despsOrd = Object.keys(desps).map(
        (key) => {return [key,desps[key]]}
    )

    despsOrd.sort(
        (p1,p2) => {return p2[1] - p1[1]}
    )
    
    var pagHTML = `
            <!DOCTYPE html>
            <head>
                <meta charset= "UTF-8">
                <title>Distribuição por Desporto</title>
                <link rel="stylesheet" href = "w3.css"/>
            </head>
                <body>
                    <div class="w3-card-4">
                        <header class="w3-container w3-red">
                            <h1>Distribuição por Desporto</h1>
                        </header>
                
                        <div class="w3-container">
                            <div class="w3-container">

                            <table class="w3-table-all">
                                <tr>
                                    <th>Desporto</th>
                                    <th>Número de Pessoas</th>
                                </tr>`
    
    for(let i=0; i<despsOrd.length;i++){
        pagHTML += `
                <tr>
                        <td>${despsOrd[i][0]}</td>
                        <td>
                            <a href="http://localhost:7778/desporto/${despsOrd[i][0]}">
                            ${despsOrd[i][1]}
                            </a>
                        </td>
                </tr>
        `
    }

    pagHTML += `
                        </table>
                        </div>
            
                    <footer class="w3-container w3-blue">
                        <h5>João Loureiro - a97257 | Engenharia Web 2023 - Universidade do Minho</h5>
                        <h5>Generated by server: ${data}</h5>
                    </footer>
                </div>
                    </body>
            </html>
        `
    
        return pagHTML
}

exports.genPagDespEscolhido = function(desporto,lista,data){
    var pagHTML = `
    <!DOCTYPE html>
    <head>
        <meta charset= "UTF-8">
        <title>Desporto ${desporto}</title>
        <link rel="stylesheet" href = "w3.css"/>
    </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-red">
                    <h1>Lista de Pessoas que praticam ${desporto}</h1>
                </header>
        
                <div class="w3-container">
                   <div class="w3-container">

                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Idade</th>
                            <th>Sexo</th>
                            <th>Cidade</th>
                        </tr>`

    for(let i=0; i<lista.length; i++){
        if (lista[i].desportos.includes(desporto)){
            pagHTML += `
                <tr>
                        <td>${lista[i].id}</td>
                        <td>
                            <a href="http://localhost:7778/pessoas/${lista[i].id}">
                            ${lista[i].nome}
                            </a>
                        </td>
                        <td>${lista[i].idade}</td>
                        <td>${lista[i].sexo}</td>
                        <td>${lista[i].morada.cidade}</td>
                </tr>
        `

        }
    }
   
    pagHTML += `
                    </table>
                    </div>
        
                <footer class="w3-container w3-blue">
                    <h5>João Loureiro - a97257 | Engenharia Web 2023 - Universidade do Minho</h5>
                    <h5>Generated by server: ${data}</h5>
                </footer>
            </div>
        </body>
</html>
    `
    return pagHTML
}

exports.genPagTopProf = function(top,lista,data){
    var profs = {}
    for(let i=0; i<lista.length;i++){
        if (!(profs.hasOwnProperty(lista[i].profissao))){
            profs[lista[i].profissao] = 0
        }
        profs[lista[i].profissao] = profs[lista[i].profissao] + 1
    }

    var profOrd = Object.keys(profs).map(
        (key) => {return [key,profs[key]]}
    )

    profOrd.sort(
        (p1,p2) => {return p2[1] - p1[1]}
    )

    const topX = profOrd.slice(0,top)

    var pagHTML = `
            <!DOCTYPE html>
            <head>
                <meta charset= "UTF-8">
                <title>Top 10 Profissões</title>
                <link rel="stylesheet" href = "w3.css"/>
            </head>
                <body>
                    <div class="w3-card-4">
                        <header class="w3-container w3-red">
                            <h1>Top 10 Profissões mais exercidas</h1>
                        </header>
                
                        <div class="w3-container">
                            <div class="w3-container">

                            <table class="w3-table-all">
                                <tr>
                                    <th>Rank</th>
                                    <th>Profissão</th>
                                    <th>Número de Pessoas</th>
                                </tr>`
    
    for(let i=0; i<topX.length;i++){
        pagHTML += `
                <tr>
                        <td><b>${i+1}</b></td>
                        <td>${topX[i][0]}</td>
                        <td>
                            <a href="http://localhost:7778/profissao/${topX[i][0]}">
                            ${topX[i][1]}
                            </a>
                        </td>
                </tr>
        `
    }
    
    pagHTML += `
                        </table>
                        </div>
            
                    <footer class="w3-container w3-blue">
                        <h5>João Loureiro - a97257 | Engenharia Web 2023 - Universidade do Minho</h5>
                        <h5>Generated by server: ${data}</h5>
                    </footer>
                </div>
                    </body>
            </html>
        `
    
        return pagHTML
}

exports.genPagProfEscolhido = function(prof,lista,data){
    var pagHTML = `
    <!DOCTYPE html>
    <head>
        <meta charset= "UTF-8">
        <title>Profissão ${prof}</title>
        <link rel="stylesheet" href = "w3.css"/>
    </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-red">
                    <h1>Lista de Pessoas que exercem ${prof}</h1>
                </header>
        
                <div class="w3-container">
                   <div class="w3-container">

                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Idade</th>
                            <th>Sexo</th>
                            <th>Cidade</th>
                        </tr>`

    for(let i=0; i<lista.length; i++){
        if (lista[i].profissao == prof){
            pagHTML += `
                <tr>
                        <td>${lista[i].id}</td>
                        <td>
                            <a href="http://localhost:7778/pessoas/${lista[i].id}">
                            ${lista[i].nome}
                            </a>
                        </td>
                        <td>${lista[i].idade}</td>
                        <td>${lista[i].sexo}</td>
                        <td>${lista[i].morada.cidade}</td>
                </tr>
        `

        }
    }
   
    pagHTML += `
                    </table>
                    </div>
        
                <footer class="w3-container w3-blue">
                    <h5>João Loureiro - a97257 | Engenharia Web 2023 - Universidade do Minho</h5>
                    <h5>Generated by server: ${data}</h5>
                </footer>
            </div>
        </body>
</html>
    `
    return pagHTML

}