exports.mainPage = function(idTarefa,users,tarefas,data){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Lista de Tarefas</title>
        </head>

        <body>
            <header class="w3-container w3-red">
                <h1><a href="/">TPC 4 - Lista de Tarefas</a></h1>
            </header>

        <div class="w3-container w3-cell">
            <a href="/users/create" class="w3-btn w3-purple"><b>Adicionar Utilizador</b></a>
            <br>    
            <form action="/tasks/create" class="w3-container w3-card-4 w3-blue" method="POST">
            <fieldset>
                <legend><b>Adicionar Tarefa</b></legend>
                <input type="hidden" name="id" value=${idTarefa}>

                <p>Insira os dados da nova tarefa que pretende criar</p>

                <p><label>Descrição da tarefa</label>
                <input class="w3-input w3-border" name="desc" type="text"></p>

                <p><label>Qual a data limite?</label>
                <input class="w3-input w3-border" type="date" name="due">
                
                <p><label>Quem a irá realizar?</label>
                <select class="w3-select" name="who">
                    <option value="" disabled selected>Escolha uma pessoa...</option>
        `
    for(let i = 0; i<users.length;i++){
        pagHTML += `
                    <option class="w3-center">${users[i].name}</option>
        `
    }

    pagHTML +=   `
                </select>

                <input type="hidden" name="done" value=false>
                </fieldset>  

                <button class="w3-btn w3-green w3-mb-2" type="submit">Enviar</button>
            </form>
        </div>



        <div class="w3-container w3-cell w3-border" style="width:50%">
            <h2>Tarefas por fazer:</h2>
`

for(let i = 0; i < tarefas.length; i++){
    if(tarefas[i].done == "false"){
        pagHTML += `
            <div class="w3-container w3-border">
                <p class="w3 right-align">
                [<a href="/tasks/edit/${tarefas[i].id}"><b>Editar</b></a>][<a href="/tasks/delete/${tarefas[i].id}"><b>Apagar</b></a>][<a href="/tasks/done/${tarefas[i].id}"><b>Feito</b></a>]
                </p>
                <p><b>Descrição:</b> ${tarefas[i].desc}</p>
                <p><b>Reponsável:</b> ${tarefas[i].who}</p>
                <p><b>Data Limite:</b> ${tarefas[i].due}</p>
            </div>
    `
    }
}

pagHTML += `
        </div>

        <div class="w3-container w3-cell w3-border" style="width:50%">
            <h2>Tarefas feitas:</h2>
`

for(let i = 0; i < tarefas.length; i++){
    if(tarefas[i].done == "true"){
        pagHTML += `
            <div class="w3-container w3-border">
                <p class="w3 right-align">
                <a href="/tasks/delete/${tarefas[i].id}"><b>Apagar</b></a>
                </p>
                <p><b>Descrição:</b> ${tarefas[i].desc}</p>
                <p><b>Reponsável:</b> ${tarefas[i].who}</p>
                <p><b>Data Limite:</b> ${tarefas[i].due}</p>
            </div>
    `
    }
}

pagHTML += `
        </div>

        <footer class="w3-container w3-yellow">
                    <h5>João Loureiro - a97257 | Engenharia Web 2023 - Universidade do Minho</h5>
                    <h5>Generated by server: ${data}</h5>
                </footer>
            </div>
        </body>
    </html>
`

return pagHTML
}

exports.userFormPage = function(idUser,data){
   var pagHTML = `
        <!DOCTYPE html>
        <html>
            <head>
                <meta charset="UTF-8"/>
                <link rel="icon" href="favicon.png"/>
                <link rel="stylesheet" href="w3.css"/>
                <title>Adicionar Utilizador</title>
            </head>

            <body>
            <div class="w3-card-4">
                <header class="w3-container w3-red">
                    <h2>Formulário de Novo Utilizador <a href="/"</h2>
                    <h3><a href="/" class="w3-btn w3-pale-red"><b>Voltar ao Início</b></a></h3>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset class="w3-sand">
                        <legend><b>Utilizador</b></legend>
                        <input type="hidden" name="id" value=${idUser}>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="name"/>
                        <label>Username</label>
                        <input class="w3-input w3-round" type="text" name="usrnm"/>
                    </fieldset>

                    <button class="w3-btn w3-green w3-mb-2" type="submit">Registar</button>

                </form>

                    <footer class="w3-container w3-yellow">
                    <h5>João Loureiro - a97257 | Engenharia Web 2023 - Universidade do Minho</h5>
                    <h5>Generated by server: ${data}</h5>
                    </footer>
            </div>
            </body>
        </html>

            `
    return pagHTML          
}

exports.tarefaFormEditPage = function(tarefa,users,data){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Editar Tarefa</title>
        </head>

        <body>
        <div class="w3-card-4">
            <header class="w3-container w3-red">
                <h2>Editar Tarefa</h2>
                <h3><a href="/" class="w3-btn w3-pale-red"><b>Voltar ao Início</b></a></h3>
            </header>
        
            <form class="w3-container w3-card-4" method="POST">
            <fieldset class="w3-sand">
                <legend><b>Tarefa</b></legend>
                <input type="hidden" name="id" value=${tarefa.id}>

                <p><label>Descrição da tarefa</label>
                <input class="w3-input w3-border" name="desc" type="text" value="${tarefa.desc}"></p>

                <p><label>Qual a data limite?</label>
                <input class="w3-input w3-border" type="date" name="due" value=${tarefa.due}>
                
                <p><label>Quem a irá realizar?</label>
                <select class="w3-select" name="who">
                    <option value=${tarefa.who} disabled selected>Escolha uma pessoa...</option>
        `
    for(let i = 0; i<users.length;i++){
        pagHTML += `
                    <option class="w3-center">${users[i].name}</option>
        `
    }

    pagHTML +=   `
                </select>

                <input type="hidden" name="done" value=false>
                </fieldset>  

                <button class="w3-btn w3-green w3-mb-2" type="submit">Enviar</button>
            </form>

                <footer class="w3-container w3-yellow">
                <h5>João Loureiro - a97257 | Engenharia Web 2023 - Universidade do Minho</h5>
                <h5>Generated by server: ${data}</h5>
                </footer>
        </div>
        </body>
    </html>

        `
    return pagHTML     
}

exports.successPage = function(data,registo){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Efetuado com sucesso</title>
        </head>

        <body>
        <div class="w3-card-4">
            <header class="w3-container w3-red">
                <h2>Efetuado com Sucesso!</h2>
            </header>
        
            <form class="w3-container">
            <p>${registo} foi efetuado com sucesso!</p>
            <a href="/" class="w3-btn w3-pale-red"><b>Voltar ao Início</b></a>
            </form>

                <footer class="w3-container w3-yellow">
                <h5>João Loureiro - a97257 | Engenharia Web 2023 - Universidade do Minho</h5>
                <h5>Generated by server: ${data}</h5>
                </footer>
        </div>
        </body>
    </html>

        `

    return pagHTML
}